"""Write docs/fresh_labeling_guide.md: the task, the 36 types with CUAD's descriptions, span lengths and one
worked example per type, all from CUAD train contracts only.

  python -m src.fresh.guide
"""

from __future__ import annotations

import json
import zlib

import numpy as np
import pandas as pd

from src import config
from src.data import load_raw_json
from src.fresh import config as F
from src.fresh.build import categories_36
from src.labels import MERGED, RARE_DROPPED

OUT = config.DOCS_DIR / "fresh_labeling_guide.md"
EXAMPLE_CHARS = 400

INTRO = """# Fresh labeling guide (version {version})

Generated by `python -m src.fresh.guide` from CUAD train contracts only. Do not edit by hand.

## The task
You will read about 30 commercial contracts filed with the SEC in 2026 and mark every clause that belongs to one
of the 36 types below, the same types CUAD's lawyers marked. The labels become the answer key for a one-time test
of several classifiers, so a missed clause counts against a model that found it, and a wrong mark rewards a model
that guessed wrong. Careful and complete matters more than fast.

## How to mark
- Open `tools/labeler/index.html`, enter your initials, and pick a contract. Wait for "text verified".
- Select the clause text with the mouse, choose its type, and press Tag. Mark the clause as CUAD would: usually
  one sentence to one section, enough text to show the obligation, right or restriction. The span-length column
  below shows what CUAD's lawyers typically marked for each type.
- **Mark every occurrence.** If a type appears in three places, mark all three.
- **One text can carry several types.** Tag the same text again with each type that applies. For example, a
  liability cap with carve-outs is both Cap On Liability (the cap) and Uncapped Liability (the carve-outs).
- **Checklist.** Every type you did not mark needs "not present" confirmed. Export is blocked until all 36 are
  settled, so an absent type is a decision, not an omission.
- Enter the agreement date as the contract states it (YYYY-MM-DD). It is recorded but not scored.
- Export one JSON file per contract and send it back. The file holds positions and types only, no contract text.

## Rules carried over from CUAD
- **Names and dates are not clause types.** Document name, parties, agreement date and effective date are not
  marked as spans. A clause that states the term or renewal (Expiration Date, Renewal Term, Notice Period To
  Terminate Renewal) or the governing law is marked, at clause length.
- **Affiliate License** is one checklist item covering both of CUAD's halves: a license that extends to the
  licensee's affiliates, and a license granted by or covering the intellectual property of the licensor's
  affiliates. Mark either.
- **Redacted text.** Mark a clause even when some of its words are redacted, if what remains shows its type.
- **Competitive Restriction Exception** marks the exceptions or carve-outs to a Non-Compete, Exclusivity or
  No-Solicit Of Customers clause, not the restriction itself (mark the restriction with its own type).
- When unsure whether a clause fits a type, mark it and keep a short list of doubts (contract id, type, the
  first few words of the clause, why) to send with the exports. Do not leave a doubt unrecorded.

## The 36 types
Span lengths are in characters: median and interquartile range of CUAD's marked spans in train contracts.
"""


def train_spans() -> pd.DataFrame:
    spans = pd.read_parquet(config.PROCESSED_DIR / "spans.parquet")
    splits = pd.read_csv(config.SPLITS_CSV)
    train = set(splits.loc[splits["split"] == "train", "contract_id"])
    pos = spans[spans["has_answer"] & spans["contract_id"].isin(train)].copy()
    pos["type"] = pos["category"].map(lambda c: MERGED.get(c, c))
    pos["chars"] = (pos["answer_end"] - pos["answer_start"]).astype(int)
    return pos[pos["type"].isin(categories_36())]


def descriptions(raw: dict) -> dict[str, str]:
    out: dict[str, list[str]] = {}
    for qa in raw["data"][0]["paragraphs"][0]["qas"]:
        category = qa["id"].rsplit("__", 1)[1]
        t = MERGED.get(category, category)
        if t in categories_36() and "Details:" in qa["question"]:
            detail = " ".join(qa["question"].split("Details:", 1)[1].split())
            out.setdefault(t, []).append(f"{category.rsplit('-', 1)[1]}: {detail}" if category in MERGED else detail)
    return {t: " ".join(sorted(v)) for t, v in out.items()}


def example(group: pd.DataFrame, t: str) -> tuple[int, str]:
    """One seeded example, among the spans within the type's interquartile range of length."""
    lo, hi = group["chars"].quantile([0.25, 0.75])
    pool = group[(group["chars"] >= lo) & (group["chars"] <= hi)].sort_values(["contract_id", "answer_start"])
    rng = np.random.default_rng([config.SEED, zlib.crc32(f"fresh_guide/{t}".encode())])
    row = pool.iloc[int(rng.integers(len(pool)))]
    text = " ".join(row["answer_text"].split())
    return int(row["contract_id"]), (text if len(text) <= EXAMPLE_CHARS
                                     else text[:EXAMPLE_CHARS].rsplit(" ", 1)[0] + " ...")


def main() -> None:
    spans = train_spans()
    desc = descriptions(load_raw_json())
    parts = [INTRO.format(version=F.GUIDE_VERSION)]
    for t in categories_36():
        g = spans[spans["type"] == t]
        q1, med, q3 = g["chars"].quantile([0.25, 0.5, 0.75]).round().astype(int)
        cid, text = example(g, t)
        rare = " (rare in CUAD; kept on the checklist so CUAD's exclusion rule applies unchanged)" if t in RARE_DROPPED else ""
        parts.append(f"\n### {t}{rare}\n- **Definition (CUAD):** {desc[t]}\n"
                     f"- **Span length:** median {med}, interquartile range {q1} to {q3} "
                     f"({len(g)} train spans in {g['contract_id'].nunique()} train contracts)\n"
                     f"- **Example (CUAD train contract {cid}):** \"{text}\"\n")
    OUT.write_text("".join(parts))
    print(f"Wrote {OUT} ({len(categories_36())} types)")
    print(json.dumps({t: int((spans["type"] == t).sum()) for t in categories_36()}))


if __name__ == "__main__":
    main()
